package platform

when ODIN_OS == .JS {
	PLATFORM :: PLATFORM_WEB
	RELEASE  :: WEB_RELEASE
	PRESS    :: WEB_PRESS
	REPEAT   :: WEB_REPEAT
} else {
	PLATFORM :: PLATFORM_GLFW
	RELEASE  :: GLFW_RELEASE
	PRESS    :: GLFW_PRESS
	REPEAT   :: GLFW_REPEAT
}
