import * as fs from "node:fs";
import * as path from "node:path";

const SRC_DIR = path.resolve(import.meta.dirname, "..", "src");
const GENERATED_MARKER = "// Code generated by scripts/build-style-vtable.ts; DO NOT EDIT.";

interface Entry {
    name: string;
    types: string[];
}

function findStyleFiles(dir: string): string[] {
    const out: string[] = [];
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, e.name);
        if (e.isDirectory()) out.push(...findStyleFiles(full));
        else if (e.isFile() && e.name.endsWith(".style")) out.push(full);
    }
    return out;
}

function parseStyle(file: string): Entry[] {
    const entries: Entry[] = [];
    const lines = fs.readFileSync(file, "utf8").split(/\r?\n/);
    lines.forEach((raw, i) => {
        const line = raw.replace(/\/\/.*$/, "").trim();
        if (line === "") return;
        const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*::\s*(.+)$/);
        if (!m) {
            throw new Error(`${file}:${i + 1}: cannot parse line: ${raw}`);
        }
        const types = m[2].split(",").map((t) => t.trim()).filter(Boolean);
        if (types.length === 0) {
            throw new Error(`${file}:${i + 1}: missing type value(s): ${raw}`);
        }
        entries.push({ name: m[1], types });
    });
    return entries;
}

function packageName(dir: string): string {
    for (const e of fs.readdirSync(dir)) {
        if (!e.endsWith(".odin")) continue;
        const src = fs.readFileSync(path.join(dir, e), "utf8");
        const m = src.match(/^\s*package\s+([A-Za-z_][A-Za-z0-9_]*)/m);
        if (m) return m[1];
    }
    return path.basename(dir);
}

function structName(base: string): string {
    if (base === "vtable") return "Style_VTable";
    const pascal = base
        .split(/[_-]/)
        .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
        .join("");
    return `${pascal}_VTable`;
}

interface Field {
    name: string;
    sig: string;
}

// A type entry is "[name:]type[ = default]", e.g. "u:unit = px" becomes the
// Odin parameter "u := px". Unnamed values get v (single) or v0, v1, ...
function fieldsFor(e: Entry): Field[] {
    const parsed = e.types.map((t) => {
        const m = t.match(/^(?:([A-Za-z_][A-Za-z0-9_]*)\s*:\s*)?([^=]+?)(?:\s*=\s*(.+))?$/);
        if (!m) throw new Error(`cannot parse type value '${t}' for '${e.name}'`);
        return m;
    });
    const unnamedCount = parsed.filter((m) => !m[1]).length;
    let unnamedIndex = 0;
    const params = parsed.map((m) => {
        const name = m[1] ?? (unnamedCount === 1 ? "v" : `v${unnamedIndex++}`);
        const type = m[2].trim();
        return m[3]
            ? { decl: `${name} := ${m[3]}`, type }
            : { decl: `${name}: ${type}`, type };
    });
    const types = params.map((p) => p.type);
    const ret = types.length === 1 ? types[0] : `(${types.join(", ")})`;
    const paramList = params.map((p) => p.decl).join(", ");
    return [
        { name: `get_${e.name}`, sig: `proc(self: ^Style) -> ${ret}` },
        { name: `set_${e.name}`, sig: `proc(self: ^Style, ${paramList}) -> ^Style` },
    ];
}

function generate(styleFile: string): void {
    const dir = path.dirname(styleFile);
    const base = path.basename(styleFile, ".style");
    const target = path.join(dir, `${base}.odin`);

    const entries = parseStyle(styleFile);
    const getters = entries.flatMap((e) => [fieldsFor(e)[0]]);
    const setters = entries.flatMap((e) => [fieldsFor(e)[1]]);
    const pad = Math.max(...[...getters, ...setters].map((f) => f.name.length)) + 1;
    const render = (f: Field) => `    ${(f.name + ":").padEnd(pad + 1)}${f.sig},`;

    const out = [
        GENERATED_MARKER,
        `// Source: ${path.relative(dir, styleFile)}`,
        `package ${packageName(dir)}`,
        "",
        `${structName(base)} :: struct #all_or_none {`,
        ...getters.map(render),
        "",
        ...setters.map(render),
        "}",
        "",
    ].join("\n");

    if (fs.existsSync(target) && !fs.readFileSync(target, "utf8").startsWith(GENERATED_MARKER)) {
        console.error(`skip ${path.relative(SRC_DIR, target)}: exists and is not generated (missing marker)`);
        return;
    }
    fs.writeFileSync(target, out, "utf8");
    console.log(`generated ${path.relative(SRC_DIR, target)} (${entries.length} entries)`);
}

function generateAll(): void {
    const files = findStyleFiles(SRC_DIR);
    if (files.length === 0) {
        console.log("no .style files found under src/");
        return;
    }
    for (const f of files) {
        try {
            generate(f);
        } catch (err) {
            console.error(err instanceof Error ? err.message : err);
        }
    }
}

generateAll();

if (process.argv.includes("--watch")) {
    console.log("watching src/ for .style changes...");
    let timer: NodeJS.Timeout | undefined;
    fs.watch(SRC_DIR, { recursive: true }, (_event, filename) => {
        if (!filename || !filename.endsWith(".style")) return;
        clearTimeout(timer);
        timer = setTimeout(generateAll, 100);
    });
}
